#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(KC_PSCR, KC_PMNS, TG(1), KC_P0, KC_INS, KC_P9, KC_P6, KC_P3, KC_PDOT, KC_P8, KC_P5, KC_P2, KC_MUTE, KC_NUM, KC_P7, KC_P4, KC_P1),
    [1] = LAYOUT(KC_F17, KC_F21, TG(2), KC_PSLS, KC_F16, KC_F20, KC_F24, KC_PAST, KC_F15, KC_F19, KC_F23, KC_PPLS, KC_F13, KC_F14, KC_F18, KC_F22, KC_PEQL),
    [2] = LAYOUT(MS_RGHT, MS_WHLR, TO(0), KC_COPY, MS_LEFT, MS_WHLL, MS_BTN6, MS_BTN3, MS_DOWN, MS_BTN8, MS_BTN5, MS_BTN2, KC_PSTE, MS_UP, MS_BTN7, MS_BTN4, MS_BTN1)
};

#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [0] = { ENCODER_CCW_CW(MS_WHLU, MS_WHLD),  ENCODER_CCW_CW(MS_WHLR, MS_WHLL)  },
    [1] = { ENCODER_CCW_CW(MS_WHLU, MS_WHLD),  ENCODER_CCW_CW(MS_WHLR, MS_WHLL)  },
    [2] = { ENCODER_CCW_CW(MS_WHLU, MS_WHLD),  ENCODER_CCW_CW(MS_WHLR, MS_WHLL)  },
};
#endif



#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

