#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(KC_PSCR, KC_PGUP, KC_PGDN, TG(1), KC_INS, KC_P9, KC_P6, KC_P3, KC_CALC, KC_P8, KC_P5, KC_P2, KC_MUTE, KC_NUM, KC_P7, KC_P4, KC_P1),
    [1] = LAYOUT(KC_F16, KC_F20, MS_BTN4, TG(0), KC_F15, KC_F19, MS_BTN3, QK_BOOT, KC_F14, KC_F18, MS_BTN2, MS_WHLR, KC_WSCH, KC_F13, KC_F17, MS_BTN1, MS_WHLL)
};



#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

